"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Activity = { id: string; type: "quiz" | "cloud" | "open"; prompt: string; options: string | null; position: number; isActive: boolean };
type Result = { answer: string; count: number };

export function Presenter({ session, activities }: { session: { id: string; title: string; code: string }; activities: Activity[] }) {
  const initial = activities.find((item) => item.isActive) ?? activities[0];
  const [activeId, setActiveId] = useState(initial?.id ?? "");
  const [results, setResults] = useState<Result[]>([]);
  const [copied, setCopied] = useState(false);
  const [origin] = useState(() => typeof window === "undefined" ? "" : window.location.origin);
  const active = activities.find((item) => item.id === activeId) ?? initial;
  const joinUrl = origin ? `${origin}/?join=${session.code}` : "";
  const qrUrl = joinUrl ? `https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=12&data=${encodeURIComponent(joinUrl)}` : "";
  const total = useMemo(() => results.reduce((sum, item) => sum + Number(item.count), 0), [results]);
  const stored = active?.options ? JSON.parse(active.options) as { choices?: string[]; correctIndices?: number[] } : {};

  useEffect(() => {
    let cancelled = false;
    async function refresh() {
      const response = await fetch(`/api/sessions?code=${session.code}`, { cache: "no-store" });
      if (response.ok && !cancelled) {
        const data = await response.json() as { active?: Activity; results?: Result[] };
        if (data.active?.id) setActiveId(data.active.id);
        setResults(data.results ?? []);
      }
    }
    void refresh();
    const timer = window.setInterval(refresh, 2000);
    return () => { cancelled = true; window.clearInterval(timer); };
  }, [session.code]);

  async function activate(activityId: string) {
    const response = await fetch("/api/creator", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "activate", sessionId: session.id, activityId }) });
    if (response.ok) {
      setActiveId(activityId);
      setResults([]);
    }
  }

  async function copyLink() {
    await navigator.clipboard.writeText(joinUrl);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  }

  return (
    <main className="presenter-shell">
      <header className="presenter-topbar">
        <Link className="brand" href="/dashboard"><span className="brand-mark">M</span><span>모아</span></Link>
        <div><span className="live-dot" /> LIVE</div>
        <Link className="secondary" href="/dashboard">제작 화면</Link>
      </header>
      <div className="presenter-layout">
        <aside className="presenter-side glass-card">
          <p className="eyebrow">LIVE SESSION</p>
          <h2>{session.title}</h2>
          <div className="join-code-card"><small>참여 코드</small><strong>{session.code.slice(0,3)} {session.code.slice(3)}</strong></div>
          {/* QR is generated by a remote image endpoint from the public join URL. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          {qrUrl && <img className="qr-image" src={qrUrl} width="210" height="210" alt={`참여 코드 ${session.code} QR`} />}
          <p className="qr-help">휴대폰 카메라로 찍으면<br />참여 화면에 바로 접속합니다.</p>
          <button className="primary wide" onClick={copyLink}>{copied ? "복사 완료 ✓" : "참여 링크 복사"}</button>
          <div className="presenter-questions">
            {activities.map((item, index) => <button className={item.id === activeId ? "active" : ""} key={item.id} onClick={() => void activate(item.id)}><span>0{index + 1}</span><b>{item.prompt}</b></button>)}
          </div>
        </aside>

        <section className={`live-results ${active.type}`}>
          <div className="live-head"><div><p className="eyebrow">{active.type === "quiz" ? "QUIZ" : active.type === "cloud" ? "WORD CLOUD" : "OPEN QUESTION"} · {activities.findIndex((item) => item.id === active.id) + 1}/{activities.length}</p><h1>{active.prompt}</h1></div><div className="response-counter"><strong>{total}</strong><span>응답</span></div></div>
          {active.type === "quiz" && <div className="live-bars">
            {(stored.choices ?? []).map((choice, index) => {
              const count = results.filter((item) => item.answer.split("|||").includes(choice)).reduce((sum, item) => sum + Number(item.count), 0);
              const percent = total ? Math.round(count / total * 100) : 0;
              return <div className={`live-bar ${stored.correctIndices?.includes(index) ? "correct" : ""}`} key={choice}><span>{String.fromCharCode(65 + index)}</span><b>{choice}{stored.correctIndices?.includes(index) && " ✓"}</b><i><em style={{ width: `${percent}%` }} /></i><strong>{count}</strong></div>;
            })}
          </div>}
          {active.type === "cloud" && <div className="live-word-cloud">{results.length ? results.map((item, index) => <span key={item.answer} style={{ fontSize: `${1.1 + Math.min(Number(item.count), 8) * .28}rem`, transform: `rotate(${index % 3 - 1}deg)` }}>{item.answer}</span>) : <p>첫 단어를 기다리고 있어요…</p>}</div>}
          {active.type === "open" && <div className="live-open-grid">{results.length ? results.map((item) => <article key={item.answer}><p>{item.answer}</p><span>{item.count}명</span></article>) : <p>첫 답변을 기다리고 있어요…</p>}</div>}
          <footer className="presenter-footer"><span>참여 링크</span><b>{joinUrl}</b><span className="sync-pill">● 2초마다 자동 집계</span></footer>
        </section>
      </div>
    </main>
  );
}
